name: Test
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   
    - name: Run test
      run: |
        coverage run -m unittest
